### ISSUE TITLE
What is version 1.0.3

### ISSUE THREAD

**Issue by brettz9** [shadiabuhilal/rtl-detect#10]
You released a version 1.0.3 recently, but I see no updates on the repo. Can you explain what this was about and why the issues were just closed? If you are deprecating or abandoning the project, can you say something so we are not concerned your account was hijacked or something?

**Comment by pdehaan** [comment]
TIL: <kbd>npm diff --diff=rtl-detect@1.0.2 --diff=rtl-detect@1.0.3</kbd>

Looks like some changes to tests, Grunt tasks, Travis config, and a curious removal of "he" (Hebrew) and "yi" (Yiddish) from the rtl locales array; filed as #11.

**Comment by orencp** [comment]
Look at the date in which 1.0.3 was released without any reasonable update. 10-May.
It's Jerusalem day. In that day, Israel has started a military operation named "Operation Wall Guardian" after rockets have been launched from Gaza strip to Jerusalem. Shadi Abu Hilal has probably decided to remove the Hebrew and Yidish languages from the RTL languages array.
See Shadi's facebook in order to get familiar with Shadi and his latest post against Israel :
https://www.facebook.com/shadiabuhilal  (I saved a video while going over his posts).
Shadi, please do not involve politics and antisemitism when uploading code to GitHub. Thanks !

**Comment by Theblueshield** [comment]
@shadiabuhilal I only have one thing to say to you and I'll tell you politely, fuc* y0u a piece of sh*t. Come to Israel, we are waiting for you. and do not forget one thing, we have some practical knowledge in cyber.
Hope I was polite.

**Comment by brettz9** [comment]
I see from `npm diff --diff=rtl-detect@1.0.3 --diff=rtl-detect@1.0.4` that the old behavior re: Hebrew and Yiddish has been restored so closing.

However, if you want to regain credibility with most users here (and many of us are no doubt grateful for the useful tool), I would think it would behoove you to mention what happened, e.g., that you made a rash action and don't intend to do this again.

Punishing all users of a language (and other users) is a pretty wide net, however asymmetric a person might feel relations with any government associated with a particular language to be, and just as any valid human rights objections are likely to be based on the principle that only those responsible should be subject to accountability, so too does the average npm user no doubt expect that they will not be subjected to retaliation for something with which they were not connected, especially where version differences are not documented and transparent.

Thank you.
