### ISSUE TITLE
Question about a simpler implementation

### ISSUE THREAD

**Issue by maneetgoyal** [shadiabuhilal/rtl-detect#9]
There's a list of RTL languages in the source code:

```js
const rtlLocales = [
        'ae',	/* Avestan */
        'ar',   /* 'العربية', Arabic */
        'arc',  /* Aramaic */
        'bcc',  /* 'بلوچی مکرانی', Southern Balochi */
        'bqi',  /* 'بختياري', Bakthiari */
        'ckb',  /* 'Soranî / کوردی', Sorani */
        'dv',   /* Dhivehi */
        'fa',   /* 'فارسی', Persian */
        'glk',  /* 'گیلکی', Gilaki */
        'he',   /* 'עברית', Hebrew */
        'ku',   /* 'Kurdî / كوردی', Kurdish */
        'mzn',  /* 'مازِرونی', Mazanderani */
        'nqo',  /* N'Ko */
        'pnb',  /* 'پنجابی', Western Punjabi */
        'ps',   /* 'پښتو', Pashto, */
        'sd',   /* 'سنڌي', Sindhi */
        'ug',   /* 'Uyghurche / ئۇيغۇرچە', Uyghur */
        'ur',   /* 'اردو', Urdu */
        'yi'    /* 'ייִדיש', Yiddish */
    ],
```

Instead of using this library, what is the downside of using simply `isRTL = rtlLocales.indexOf(myLocale) !== -1`?

**Comment by brettz9** [comment]
The language portion of a language tag/locale is often followed by other information such as region (sometimes called country codes), like `fa-IR` for Persian (Farsi) of the variety from Iran. The project parses the language tag so it looks at the language portion only. Other portions include script, variant, extension, and privateuse. See https://tools.ietf.org/html/bcp47#page-1-5 for the language tag structure.

Note that #2 was filed because those locales which are more explicit in listing a specific script are not currently recognized in this package, e.g., if English were to be written in the Arabic script, it would be `en-Arab`, and in such a case, it should be indicated as right-to-left despite the language being English.

But for the simpler cases where there is only a region code, this package will factor that out when doing the comparison and give the most likely script directionality based on what the script usually used for that language is (e.g., Persian is generally in the Arabic script, and English in the Latin script, so `rtl-detect` guesses based on just the usual scenario).

Note that https://github.com/tc39/ecma402/issues/205 was filed to allow JavaScript itself to provide this information, and https://github.com/FrankYFTang/proposal-intl-locale-info/ was created for one proposal to add to the [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) object, but these are not currently implemented anywhere, as far as I know.

**Comment by maneetgoyal** [comment]
Thanks for your superb response @brettz9.

How about this then? Does it also seem a bit unsafe?

```js
function isRTL(inputLocale) {

  const rtlLocales = [
        'ae',	/* Avestan */
        'ar',   /* 'العربية', Arabic */
        'arc',  /* Aramaic */
        'bcc',  /* 'بلوچی مکرانی', Southern Balochi */
        'bqi',  /* 'بختياري', Bakthiari */
        'ckb',  /* 'Soranî / کوردی', Sorani */
        'dv',   /* Dhivehi */
        'fa',   /* 'فارسی', Persian */
        'glk',  /* 'گیلکی', Gilaki */
        'he',   /* 'עברית', Hebrew */
        'ku',   /* 'Kurdî / كوردی', Kurdish */
        'mzn',  /* 'مازِرونی', Mazanderani */
        'nqo',  /* N'Ko */
        'pnb',  /* 'پنجابی', Western Punjabi */
        'ps',   /* 'پښتو', Pashto, */
        'sd',   /* 'سنڌي', Sindhi */
        'ug',   /* 'Uyghurche / ئۇيغۇرچە', Uyghur */
        'ur',   /* 'اردو', Urdu */
        'yi'    /* 'ייִדיש', Yiddish */
    ];

  return rtlLocales.some((ele) => { // checking all members of the rtlLocales array
    return inputLocale.indexOf(ele) !== -1; // string comparison
  };

}
```

I think it's a good tiny and handy library but just trying to justify the use of this library to myself. Been searching for other implementations of `isRTL` as well. For instance, [here's](https://github.com/LLK/scratch-l10n/blob/master/src/supported-locales.js#L116) one. But based on your explanation, it doesn't like a robust solution. Here's [one more](https://github.com/microsoft/fast/tree/master/packages/utilities/fast-web-utilities#isrtl) by Microsoft (but the implementation seems to be missing there).

**Comment by brettz9** [comment]
I haven't really dug in to see if that code can be optimized, but your implementation would not be safe as it would give a false positive for something like `es-ar` (Argentinian Spanish) which should be LTR.

And yeah, the MS one indeed appears incomplete.

**Comment by maneetgoyal** [comment]
Thanks @brettz9, it was a great help :)

**Comment by maneetgoyal** [comment]
Closing the issue as my question was addressed.
